management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: ["*"]
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: client


